pipeline {
    agent any

    environment {
        IMAGE_NAME = 'harikrishna941/java-ci-app'
        DOCKERHUB_CREDS = 'dockerhub-creds' // Jenkins credentials ID
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }

        stage('Build Java Application') {
            steps {
                dir('java-ci-app') { 
                echo 'Building Java application with Maven...'
                sh 'mvn clean package -DskipTests'
            }
            }
        }

        stage('Docker Build & Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKERHUB_CREDS}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    
                    # Build Docker image
                    docker build -t ${IMAGE_NAME}:latest .
                    
                    # Push Docker image to Docker Hub
                    docker push ${IMAGE_NAME}:latest
                    
                    docker logout
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
